CREATE TABLE monsto_strike_shot_type (
	id					INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at			TIMESTAMP DEFAULT 0 NOT NULL,
	updated_at			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	name				VARCHAR(32) DEFAULT NULL,
	rare				INT DEFAULT 0,
	attribute_type		VARCHAR(32) DEFAULT NULL,
	from_god			BOOLEAN DEFAULT FALSE,
	bean_beast_stones	INT DEFAULT 0,
	beast_stones		INT DEFAULT 0,
	big_beast_stones	INT DEFAULT 0,
	red_beast_stones	INT DEFAULT 0,
	red_beast_gems		INT DEFAULT 0,
	blue_beast_stones	INT DEFAULT 0,
	blue_beast_gems		INT DEFAULT 0,
	green_beast_stones	INT DEFAULT 0,
	green_beast_gems	INT DEFAULT 0,
	dark_beast_stones	INT DEFAULT 0,
	dark_beast_gems		INT DEFAULT 0,
	light_beast_stones	INT DEFAULT 0,
	light_beast_gems	INT DEFAULT 0,
	beast_god_gems		INT DEFAULT 0,
);
