CREATE TABLE monsto_character_type (
	id					INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	created_at			TIMESTAMP DEFAULT 0 NOT NULL,
	updated_at			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	name				VARCHAR(32) DEFAULT NULL,
	display_string		VARCHAR(64) DEFAULT NULL,
	description			VARCHAR(512) DEFAULT NULL,
	rare				INT DEFAULT 0,
	god					BOOLEAN DEFAULT FALSE,
	ball_type			VARCHAR(32) DEFAULT NULL,
	monster_type		VARCHAR(32) DEFAULT NULL,
	attribute_type		VARCHAR(32) DEFAULT NULL,
	species_type		VARCHAR(32) DEFAULT NULL,
	ability1_type		VARCHAR(32) DEFAULT NULL,
	ability2_type		VARCHAR(32) DEFAULT NULL,
	gauge_ability_type	VARCHAR(32) DEFAULT NULL,
	friend_combo1		VARCHAR(32) DEFAULT NULL,
	friend_combo2		VARCHAR(32) DEFAULT NULL,
	strike_shot			VARCHAR(32) DEFAULT NULL,
	strike_docking		VARCHAR(32) DEFAULT NULL,
	max_hp				INT DEFAULT 0,
	max_attack			INT DEFAULT 0,
	max_speed			INT DEFAULT 0,
	tas_max_hp			INT DEFAULT 0,
	tas_max_attack		INT DEFAULT 0,
	tas_max_speed		INT DEFAULT 0,
	max_ruck			INT DEFAULT 0,
	bonus_ruck			INT DEFAULT 0,
	book_num			INT DEFAULT 0,
	internal_id			INT DEFAULT 0,
	thumbnail			TEXT DEFAULT NULL,
	image				TEXT DEFAULT NULL,
	before_monster_id	INT DEFAULT 0,
	evolution_monster_id	INT DEFAULT 0,
	god_evolution_monster1_id	INT DEFAULT 0,
	god_evolution_monster2_id	INT DEFAULT 0,
	evolution_item_type				VARCHAR(32),
	evolution_item_type_from_god	VARCHAR(32),
	god_evolution_material_monster11_id	INT DEFAULT 0,
	god_evolution_material_monster12_id	INT DEFAULT 0,
	god_evolution_material_monster13_id	INT DEFAULT 0,
	god_evolution_material_monster14_id	INT DEFAULT 0,
	god_evolution_material_monster11_ruck	INT DEFAULT 0,
	god_evolution_material_monster12_ruck	INT DEFAULT 0,
	god_evolution_material_monster13_ruck	INT DEFAULT 0,
	god_evolution_material_monster14_ruck	INT DEFAULT 0,
	god_evolution_material_monster21_id	INT DEFAULT 0,
	god_evolution_material_monster22_id	INT DEFAULT 0,
	god_evolution_material_monster23_id	INT DEFAULT 0,
	god_evolution_material_monster24_id	INT DEFAULT 0,
	god_evolution_material_monster21_ruck	INT DEFAULT 0,
	god_evolution_material_monster22_ruck	INT DEFAULT 0,
	god_evolution_material_monster23_ruck	INT DEFAULT 0,
	god_evolution_material_monster24_ruck	INT DEFAULT 0,
	UNIQUE(name)
);
